language: node_js
#sudo: required

# safelist
branches:
  only:
  - gmv

cache:
 directories:
    - '$HOME/.local/share/heroku/plugins/node_modules'
    - '$HOME/.nvm/v0.10.48/lib/node_modules'
    - '$HOME/.sonarscanner/cache'

addons:
  sonarcloud:
    organization: "el-bid-github" # the key of the org you chose at step #3
    token:
        secure: "tm7MC+ibZUizBDrDJ53ySxCZBbX6WcLEczh3npM8V6zMKcaVwPMS7mZdpLvl/RdlgVS9G0h/O5+osgKzP3wrfs9Q3Sp9NPz1T93H6YSxEqeY8XXRk6xT4Uup+tMiI5bUThg4S4L9UbMrqEwJ76lH3ksX9SE5vTEsEwv88/+jfMe7L1VnbDMg3rV8i9iN5j08RnNdKWQrXXuuVP1Q4u2X5zXe7xniR6IvKfmVyRUqQ2kuEqLGtO5BA2Kh/OQtqAC2mquC+oxMceGTW7xzp7B+FB7p7wwt8J5sjWwR1E/nI8x3Y4KwFSKXY1t2g+iuXTibZ9TEquLyVYTNrRnNZKtTyjD1FpuAd+nqb1H9QNJLqE9W+bPPT+t2e110+6JloCM8b92j98Oh54JlhoaknF0udQSzNHE8p4tvkaI6upr2ygXdp5iC0IRxK/2IWhNxblvkj4l59Ct3Cuy943oj0UmN0irmNiSEECR63p7aywAh/8V9mYUQmPk9Re/MNEyrmkTrzjkc1V7NHaSEjN7swfg3g0olyb8jmW/Cgy+RpWdDWH8rKqzef61k7TTcIQjXhH86bjZsvwVqrF9yc9VwkOABT0bET0Wny1V2FPKbRrz3nnQMxQ+YIXksoHImJlJOPFxUuQXEGd4r+yj2mdjpQHUf5Rhrfvta9dULRyOfB4J0RuI="
    branches:
      - gmv

#before_install:

install:
  - cd Proceso\ ETL
  - npm install -g .

script:
  - sonar-scanner

#after_script:
  # brand
  # package
  # qa