
-- ------------------------------------------------------
-- LOAD ODS.KIC_SRC_MOOCS_USER
-- ------------------------------------------------------
UPDATE STG.KIC_STG_MOOCS_USER
set LAST_LOGIN=NULL
WHERE CAST(LAST_LOGIN AS CHAR(26)) = '0000-00-00 00:00:00.000000';

UPDATE STG.KIC_STG_MOOCS_USER
set STG_EXT_TS=CURRENT_TIMESTAMP(6)
WHERE CAST(STG_EXT_TS AS CHAR(26)) = '0000-00-00 00:00:00.000000';

TRUNCATE TABLE ODS.KIC_SRC_MOOCS_USER;
ALTER TABLE ODS.KIC_SRC_MOOCS_USER DROP INDEX ix_user_user_id;

INSERT INTO ODS.KIC_SRC_MOOCS_USER *
FROM STG.KIC_STG_MOOCS_USER
group by ID;
CREATE UNIQUE INDEX ix_user_user_id ON ODS.KIC_SRC_MOOCS_USER ( ID );

-- ------------------------------------------------------
-- LOAD STG.KIC_MOOCS_USERPROFILE
-- ------------------------------------------------------
UPDATE STG.KIC_STG_MOOCS_USERPROFILE SET PROFILE_IMAGE_UPLOADED_AT = NULL
WHERE CAST(PROFILE_IMAGE_UPLOADED_AT AS CHAR(26)) = '0000-00-00 00:00:00.000000';

TRUNCATE TABLE ODS.KIC_SRC_MOOCS_USERPROFILE;

INSERT INTO ODS.KIC_SRC_MOOCS_USERPROFILE
SELECT * FROM STG.KIC_STG_MOOCS_USERPROFILE;

-- ------------------------------------------------------
-- LOAD ODS.KIC_SRC_MOOCS_CERTIFICATES
-- ------------------------------------------------------
UPDATE STG.KIC_SRC_MOOCS_CERTIFICATES SET CREATED_DATE = NULL
WHERE CAST(CREATED_DATE AS CHAR(26)) = '0000-00-00 00:00:00.000000';

UPDATE STG.KIC_SRC_MOOCS_CERTIFICATES SET MODIFIED_DATE = NULL
WHERE CAST(MODIFIED_DATE AS CHAR(26)) = '0000-00-00 00:00:00.000000';


TRUNCATE TABLE ODS.KIC_SRC_MOOCS_CERTIFICATES;
ALTER TABLE ODS.KIC_SRC_MOOCS_CERTIFICATES DROP INDEX ix_cert_course_user_id;

INSERT INTO ODS.KIC_SRC_MOOCS_CERTIFICATES
SELECT * FROM STG.KIC_STG_MOOCS_CERTIFICATES;

CREATE UNIQUE INDEX ix_cert_course_user_id ON ODS.KIC_SRC_MOOCS_CERTIFICATES ( COURSE_ID, USER_ID );
-- ------------------------------------------------------
-- LOAD ODS.KIC_SRC_MOOCS_CW_STUDENTMODULE
-- ------------------------------------------------------
update STG.KIC_STG_MOOCS_CW_STUDENTMODULE set CREATED=NULL;
TRUNCATE TABLE ODS.KIC_SRC_MOOCS_CW_STUDENTMODULE;
INSERT INTO ODS.KIC_SRC_MOOCS_CW_STUDENTMODULE
SELECT
  `ID`
  ,`MODULE_TYPE`
  ,`MODULE_ID`
  ,`STUDENT_ID`
  ,`GRADE`
  ,`CREATED`
  ,`MODIFIED`
  ,`MAX_GRADE`
  ,`DONE`
  ,`COURSE_ID`
  ,`STG_EXT_TS`
  ,`TRAN_TYP`
FROM STG.KIC_STG_MOOCS_CW_STUDENTMODULE;

-- ------------------------------------------------------
-- LOAD ODS.KIC_SRC_MOOCS_COURSEGRADE
-- ------------------------------------------------------
TRUNCATE TABLE ODS.KIC_SRC_MOOCS_COURSEGRADE;
INSERT INTO ODS.KIC_SRC_MOOCS_COURSEGRADE
SELECT * FROM STG.KIC_STG_MOOCS_COURSEGRADE;

-- ------------------------------------------------------
-- LOAD ODS.KIC_SRC_MOOCS_USERPROFILE / grades_persistentsubsectiongrade
-- ------------------------------------------------------
TRUNCATE TABLE ODS.KIC_SRC_MOOCS_SUBSECTIONGRADE;
INSERT INTO ODS.KIC_SRC_MOOCS_SUBSECTIONGRADE
SELECT * FROM STG.KIC_STG_MOOCS_SUBSECTIONGRADE;

-- ------------------------------------------------------
-- LOAD ODS.KIC_SRC_MOOCS_ANONYMOUSUSERID
-- ------------------------------------------------------
TRUNCATE TABLE ODS.KIC_SRC_MOOCS_ANONYMOUSUSERID;
INSERT INTO ODS.KIC_SRC_MOOCS_ANONYMOUSUSERID
SELECT * FROM STG.KIC_STG_MOOCS_ANONYMOUSUSERID;

-- ------------------------------------------------------
-- LOAD ODS.KIC_SRC_MOOCS_STUDENTROLE
-- ------------------------------------------------------
TRUNCATE TABLE ODS.KIC_SRC_MOOCS_STUDENTROLE;
INSERT INTO ODS.KIC_SRC_MOOCS_STUDENTROLE
SELECT * FROM STG.KIC_STG_MOOCS_STUDENTROLE;

-- ------------------------------------------------------
-- LOAD ODS.KIC_SRC_MOOCS_ANONYMOUSUSERID
-- ------------------------------------------------------
TRUNCATE TABLE ODS.KIC_SRC_MOOCS_ENROLLMENT;
INSERT INTO ODS.KIC_SRC_MOOCS_ENROLLMENT
SELECT * FROM STG.KIC_STG_MOOCS_ENROLLMENT;

-- ------------------------------------------------------
-- LOAD ODS.KIC_SRC_MOOCS_STUDENTLANG
-- ------------------------------------------------------
TRUNCATE TABLE ODS.KIC_SRC_MOOCS_STUDENTLANG;
INSERT INTO ODS.KIC_SRC_MOOCS_STUDENTLANG
SELECT * FROM STG.KIC_STG_MOOCS_STUDENTLANG;

-- ------------------------------------------------------
-- LOAD ODS.KIC_SRC_MOOCS_USER_TO_ID
-- ------------------------------------------------------
TRUNCATE TABLE ODS.KIC_SRC_MOOCS_USER_TO_ID;
INSERT INTO ODS.KIC_SRC_MOOCS_USER_TO_ID
SELECT * FROM STG.KIC_STG_MOOCS_USER_TO_ID;

-- ------------------------------------------------------
-- LOAD ODS.KIC_SRC_MOOCS_COURSES
-- ------------------------------------------------------
UPDATE STG.KIC_STG_MOOCS_COURSES set START_DATE=NULL;
UPDATE STG.KIC_STG_MOOCS_COURSES set END_DATE=NULL;

TRUNCATE TABLE ODS.KIC_SRC_MOOCS_COURSES;
ALTER TABLE ODS.KIC_SRC_MOOCS_COURSES DROP INDEX ix_courses_course_id;

INSERT INTO ODs.KIC_SRC_MOOCS_COURSES
SELECT * FROM STG.KIC_STG_MOOCS_COURSES;

CREATE UNIQUE INDEX ix_courses_course_id ON ODS.KIC_SRC_MOOCS_COURSES ( STUDIO_ID );
-- ------------------------------------------------------
-- LOAD ODS.KIC_SRC_MOOCS_USER_LOCATION
-- ------------------------------------------------------
TRUNCATE TABLE ODS.KIC_SRC_MOOCS_USER_LOCATION;
ALTER TABLE ODS.KIC_SRC_MOOCS_USER_LOCATION DROP INDEX ix_courses_course_id;

INSERT INTO ODS.KIC_SRC_MOOCS_USER_LOCATION
SELECT * FROM STG.KIC_STG_MOOCS_USER_LOCATION;

CREATE UNIQUE INDEX ix_courses_course_id ON ODS.KIC_SRC_MOOCS_USER_LOCATION ( USER_ID );

-- ------------------------------------------------------
-- LOAD STG.KIC_SRC_MOOCS_IDB_LOCATION
-- ------------------------------------------------------
TRUNCATE TABLE ODS.KIC_SRC_MOOCS_IDB_LOCATION;
ALTER TABLE ODS.KIC_SRC_MOOCS_IDB_LOCATION DROP INDEX ix_idblocation_sigla_idbx;

INSERT INTO ODS.KIC_SRC_MOOCS_IDB_LOCATION
SELECT * FROM STG.KIC_STG_MOOCS_IDB_LOCATION;

CREATE UNIQUE INDEX ix_idblocation_sigla_idbx ON ODS.KIC_SRC_MOOCS_IDB_LOCATION ( SIGLA_IDBX );

-- ------------------------------------------------------
--  SRC AUX TABLES
-- ------------------------------------------------------

-- ------------------------------------------------------
-- LOAD ODS.KIC_SRC_MOOCS_STUDENTPROGRESS 13 minutos
-- ------------------------------------------------------
ALTER TABLE ODS.KIC_SRC_MOOCS_STUDENTPROGRESS DROP INDEX ix_student_pro_course_user_id;

TRUNCATE TABLE ODS.KIC_SRC_MOOCS_STUDENTPROGRESS;

INSERT INTO ODS.KIC_SRC_MOOCS_STUDENTPROGRESS (COURSE_ID, STUDENT_ID, INTERACTION)
SELECT COURSE_ID, STUDENT_ID, COUNT(*) AS INTERACTION FROM ODS.KIC_SRC_MOOCS_CW_STUDENTMODULE
WHERE STUDENT_ID>0 and COURSE_ID<>'na' GROUP BY COURSE_ID, STUDENT_ID;

CREATE UNIQUE INDEX ix_student_pro_course_user_id ON ODS.KIC_SRC_MOOCS_STUDENTPROGRESS ( COURSE_ID, STUDENT_ID );

-- ------------------------------------------------------
--  LOAD ODS KIC_ODS_MOOCS 130 segundos
-- ------------------------------------------------------
TRUNCATE TABLE ODS.KIC_ODS_MOOCS_USER_ENROLL;
INSERT INTO ODS.KIC_ODS_MOOCS_USER_ENROLL

SELECT
coalesce(msp.INTERACTION/maxsp.MAX_INTERACTION*100,0) AS PERCENTAGE_PROGRESS,
coalesce(msp.INTERACTION,0) AS PROGRESS,
(SUBSTRING_INDEX(SUBSTR(mu.EMAIL, INSTR(mu.EMAIL, '@') + 1),'.',1)) AS CORPORATE_DOMAIN,
mup.COUNTRY AS COUNTRY,
coalesce(mcn.STUDIO_ID,me.COURSE_ID) AS COURSE_ID,
me.CREATED AS CREATED,
mu.DATE_JOINED AS DATE_JOINED,
coalesce(mu.email,'anon') AS EMAIL,
mup.GENDER AS GENDER,
mup.LEVEL_OF_EDUCATION AS LEVEL_OF_EDUCATION,
mc.MODE AS MODE,

NULL AS passed_timestamp,

mc.GRADE AS PERCENT_GRADE,
mc.STATUSV AS STATUS,
me.USER_ID AS USER_ID,
mu.USERNAME AS USERNAME,
mup.YEAR_OF_BIRTH AS YEAR_OF_BIRTH,
1 AS ENROLLMENT,
(CASE WHEN msp.INTERACTION>0 AND msp.INTERACTION<50 THEN 1 ELSE 0 END) AS EXPLORER,
(CASE WHEN msp.INTERACTION>=50 THEN 1 ELSE 0 END) AS ADVANCED,
(CASE WHEN mc.GRADE>0.649 THEN 1 ELSE 0 END) AS COMPLETED,
(CASE WHEN mc.STATUSV ='downloadable' THEN 1 ELSE 0 END) AS CERTIFIED,
(CASE WHEN mc.STATUSV ='downloadable' THEN 'CERTIFIED'
  WHEN mc.GRADE>0.649 THEN 'COMPLETED'
  WHEN msp.INTERACTION>=50 THEN 'ADVANCED'
  WHEN msp.INTERACTION>0 THEN 'EXPLORER'
  ELSE 'ENROLLMENT' END) AS STUDENT_TYPE,

(CASE
  WHEN YEAR(me.CREATED)-mup.YEAR_OF_BIRTH < 10 then ""
  WHEN YEAR(me.CREATED)-mup.YEAR_OF_BIRTH < 18 then "<18"
  WHEN YEAR(me.CREATED)-mup.YEAR_OF_BIRTH <= 25 then "18 - 25"
  WHEN YEAR(me.CREATED)-mup.YEAR_OF_BIRTH <= 39 then "26 - 39"
  WHEN YEAR(me.CREATED)-mup.YEAR_OF_BIRTH <= 62 then "40 - 62"
  WHEN YEAR(me.CREATED)-mup.YEAR_OF_BIRTH <= 62 AND YEAR(me.CREATED)-mup.YEAR_OF_BIRTH<90 then ">63"
  ELSE ""
  END) AS GROUP_AGE,
mcn.NAME AS COURSE_NAME,
mcn.SME AS SME,
mcn.START_DATE AS START_DATE,
mcn.END_DATE AS END_DATE,
mul.IP AS IP,
mul.TM AS TM,
mul.IP_CITY_NAME AS IP_CITY_NAME,
mul.IP_COUNTRY_ISO AS IP_COUNTRY_ISO,
mul.IP_COUNTRY_NAME AS IP_COUNTRY_NAME,
mul.IP_LATITUDE  AS IP_LATITUDE,
mul.IP_LONGITUDE  AS IP_LONGITUDE,
mul.IP_POSTAL_CODE  AS IP_POSTAL_CODE,
mul.IP_SUBDIVISION_NAME  AS IP_SUBDIVISION_NAME,
coalesce(mil.PAIS,IP_COUNTRY_NAME) AS PAIS,
mil.SIGLA_BID AS SIGLA_BID,
mil.SIGLA_IDBX AS SIGLA_IDBX,
mil.SIGLA_INTERNACIONAL AS SIGLA_INTERNACIONAL,
mil.REGION AS REGION,
mil.IDB_GROUP_CODE AS IDB_GROUP,
mil.REGION_NM AS REGION_NM
FROM
ODS.KIC_SRC_MOOCS_ENROLLMENT me
LEFT JOIN
ODS.KIC_SRC_MOOCS_CERTIFICATES mc ON me.COURSE_ID=mc.COURSE_ID AND me.USER_ID=mc.USER_ID
LEFT JOIN
ODS.KIC_SRC_MOOCS_COURSES mcn ON me.COURSE_ID=mcn.STUDIO_ID2
LEFT JOIN
ODS.KIC_SRC_MOOCS_USER mu ON me.USER_ID=mu.ID
LEFT JOIN
ODS.KIC_SRC_MOOCS_USERPROFILE mup ON mu.id=mup.USER_ID
LEFT JOIN
ODS.KIC_SRC_MOOCS_USER_LOCATION mul ON mu.id=mul.USER_ID
LEFT JOIN
ODS.KIC_SRC_MOOCS_IDB_LOCATION mil ON mup.country=mil.SIGLA_IDBX
LEFT JOIN
ODS.KIC_SRC_MOOCS_STUDENTPROGRESS msp ON me.USER_ID=msp.STUDENT_ID AND me.COURSE_ID=msp.COURSE_ID
LEFT JOIN
(SELECT COURSE_ID, MAX(INTERACTION) AS MAX_INTERACTION FROM ODS.KIC_SRC_MOOCS_STUDENTPROGRESS GROUP BY COURSE_ID) maxsp
 ON me.COURSE_ID=maxsp.COURSE_ID;

 -- ------------------------------------------------------
 --  LOAD ODS KIC_ODS_MOOCS_USER_ENROLL_ANONYM 130 segundos
 -- ------------------------------------------------------
TRUNCATE TABLE ODS.KIC_ODS_MOOCS_USER_ENROLL_ANONYM;
INSERT INTO ODS.KIC_ODS_MOOCS_USER_ENROLL_ANONYM
 SELECT
 	ue.PERCENTAGE_PROGRESS
 ,	ue.PROGRESS
 ,	ue.CORPORATE_DOMAIN
 ,	ue.COUNTRY
 ,	ue.COURSE_ID
 ,	ue.CREATED
 ,	ue.DATE_JOINED
 ,	'anon' AS EMAIL
 ,	ue.GENDER
 ,	ue.LEVEL_OF_EDUCATION
 ,	ue.MODE
 ,	ue.PASSED_TIMESTAMP
 ,	ue.PERCENT_GRADE
 ,	ue.STATUS
 ,	ma.ANONYMOUS_USER_ID AS USER_ID
 ,	'anon' AS USERNAME
 ,	ue.YEAR_OF_BIRTH
 ,	ue.ENROLLMENT
 ,	ue.EXPLORER
 ,	ue.ADVANCED
 ,	ue.COMPLETED
 ,	ue.CERTIFIED
 ,	ue.STUDENT_TYPE
 ,	ue.GROUP_AGE
 ,	ue.COURSE_NAME
 ,	ue.SME
 ,	ue.START_DATE
 ,	ue.END_DATE
 ,	ue.IP
 ,	ue.TM
 ,	ue.IP_CITY_NAME
 ,	ue.IP_COUNTRY_ISO
 ,	ue.IP_COUNTRY_NAME
 ,	ue.IP_LATITUDE
 ,	ue.IP_LONGITUDE
 ,	ue.IP_POSTAL_CODE
 ,	ue.IP_SUBDIVISION_NAME
 ,	ue.PAIS
 ,	ue.SIGLA_BID
 ,	ue.SIGLA_IDBX
 ,	ue.SIGLA_INTERNACIONAL
 ,	ue.REGION
 ,	ue.IDB_GROUP
 ,	ue.NOMBRE_REGION
 FROM ODS.KIC_ODS_MOOCS_USER_ENROLL ue
 JOIN ODS.KIC_SRC_MOOCS_ANONYMOUSUSERID ma
 USING(user_id ;
