
-- ------------------------------------------------------
-- LOAD ODS.KIC_SRC_MOOCS_USER
-- ------------------------------------------------------
UPDATE STG.KIC_STG_MOOCS_USER
set LAST_LOGIN=NULL
WHERE CAST(LAST_LOGIN AS CHAR(26)) = '0000-00-00 00:00:00.000000'

TRUNCATE TABLE ODS.KIC_SRC_MOOCS_USER;
ALTER TABLE ODS.KIC_SRC_MOOCS_USER DROP INDEX ix_user_user_id;

INSERT INTO ODS.KIC_SRC_MOOCS_USER (`ID`,`USERNAME`,`FIRST_NAME`,`LAST_NAME`,`EMAIL`,`PASSWORD`,`IS_STAFF`
,`IS_ACTIVE`,`IS_SUPERUSER`,`LAST_LOGIN`,`DATE_JOINED`)
SELECT
`ID`,MAX(`USERNAME`),MAX(`FIRST_NAME`),MAX(`LAST_NAME`),MAX(`EMAIL`),MAX(`PASSWORD`),MAX(`IS_STAFF`)
,MAX(`IS_ACTIVE`),MAX(`IS_SUPERUSER`),MAX(`LAST_LOGIN`),MAX(`DATE_JOINED`)
FROM STG.KIC_STG_MOOCS_USER
group by ID;
CREATE UNIQUE INDEX ix_user_user_id ON ODS.KIC_SRC_MOOCS_USER ( ID );

-- ------------------------------------------------------
-- LOAD STG.KIC_MOOCS_USERPROFILE
-- ------------------------------------------------------
TRUNCATE TABLE ODS.KIC_SRC_MOOCS_USERPROFILE;
ALTER TABLE ODS.KIC_SRC_MOOCS_USERPROFILE DROP INDEX ix_userprofile_user_id;

INSERT INTO ODS.KIC_SRC_MOOCS_USERPROFILE
SELECT * FROM STG.KIC_STG_MOOCS_USERPROFILE;

CREATE UNIQUE INDEX ix_userprofile_user_id ON ODS.KIC_SRC_MOOCS_USERPROFILE ( USER_ID );
-- ------------------------------------------------------
-- LOAD ODS.KIC_SRC_MOOCS_CERTIFICATES
-- ------------------------------------------------------
TRUNCATE TABLE ODS.KIC_SRC_MOOCS_CERTIFICATES;
ALTER TABLE ODS.KIC_SRC_MOOCS_CERTIFICATES DROP INDEX ix_cert_course_user_id;

INSERT INTO ODS.KIC_SRC_MOOCS_CERTIFICATES
SELECT * FROM STG.KIC_STG_MOOCS_CERTIFICATES;

CREATE UNIQUE INDEX ix_cert_course_user_id ON ODS.KIC_SRC_MOOCS_CERTIFICATES ( COURSE_ID, USER_ID );
-- ------------------------------------------------------
-- LOAD ODS.KIC_SRC_MOOCS_CW_STUDENTMODULE
-- ------------------------------------------------------
update STG.KIC_STG_MOOCS_CW_STUDENTMODULE set CREATED=NULL;
TRUNCATE TABLE ODS.KIC_SRC_MOOCS_CW_STUDENTMODULE;
INSERT INTO ODS.KIC_SRC_MOOCS_CW_STUDENTMODULE
SELECT
  `ID`
  ,`MODULE_TYPE`
  ,`MODULE_ID`
  ,`STUDENT_ID`
  ,`GRADE`
  ,`CREATED`
  ,`MODIFIED`
  ,`MAX_GRADE`
  ,`DONE`
  ,`COURSE_ID`
  ,`STG_EXT_TS`
  ,`TRAN_TYP`
FROM STG.KIC_STG_MOOCS_CW_STUDENTMODULE;

-- ------------------------------------------------------
-- LOAD ODS.KIC_SRC_MOOCS_COURSEGRADE
-- ------------------------------------------------------
TRUNCATE TABLE ODS.KIC_SRC_MOOCS_COURSEGRADE;
INSERT INTO ODS.KIC_SRC_MOOCS_COURSEGRADE
SELECT * FROM STG.KIC_STG_MOOCS_COURSEGRADE;

-- ------------------------------------------------------
-- LOAD ODS.KIC_SRC_MOOCS_USERPROFILE / grades_persistentsubsectiongrade
-- ------------------------------------------------------
TRUNCATE TABLE ODS.KIC_SRC_MOOCS_SUBSECTIONGRADE;
INSERT INTO ODS.KIC_SRC_MOOCS_SUBSECTIONGRADE
SELECT * FROM STG.KIC_STG_MOOCS_SUBSECTIONGRADE;

-- ------------------------------------------------------
-- LOAD ODS.KIC_SRC_MOOCS_ANONYMOUSUSERID
-- ------------------------------------------------------
TRUNCATE TABLE ODS.KIC_SRC_MOOCS_ANONYMOUSUSERID;
INSERT INTO ODS.KIC_SRC_MOOCS_ANONYMOUSUSERID
SELECT * FROM STG.KIC_STG_MOOCS_ANONYMOUSUSERID;

-- ------------------------------------------------------
-- LOAD ODS.KIC_SRC_MOOCS_STUDENTROLE
-- ------------------------------------------------------
TRUNCATE TABLE ODS.KIC_SRC_MOOCS_STUDENTROLE;
INSERT INTO ODS.KIC_SRC_MOOCS_STUDENTROLE
SELECT * FROM STG.KIC_STG_MOOCS_STUDENTROLE;

-- ------------------------------------------------------
-- LOAD ODS.KIC_SRC_MOOCS_ANONYMOUSUSERID
-- ------------------------------------------------------
TRUNCATE TABLE ODS.KIC_SRC_MOOCS_ENROLLMENT;
INSERT INTO ODS.KIC_SRC_MOOCS_ENROLLMENT
SELECT * FROM STG.KIC_STG_MOOCS_ENROLLMENT;

-- ------------------------------------------------------
-- LOAD ODS.KIC_SRC_MOOCS_STUDENTLANG
-- ------------------------------------------------------
TRUNCATE TABLE ODS.KIC_SRC_MOOCS_STUDENTLANG;
INSERT INTO ODS.KIC_SRC_MOOCS_STUDENTLANG
SELECT * FROM STG.KIC_STG_MOOCS_STUDENTLANG;

-- ------------------------------------------------------
-- LOAD ODS.KIC_SRC_MOOCS_USER_TO_ID
-- ------------------------------------------------------
TRUNCATE TABLE ODS.KIC_SRC_MOOCS_USER_TO_ID;
INSERT INTO ODS.KIC_SRC_MOOCS_USER_TO_ID
SELECT * FROM STG.KIC_STG_MOOCS_USER_TO_ID;

-- ------------------------------------------------------
-- LOAD ODS.KIC_SRC_MOOCS_COURSES
-- ------------------------------------------------------
UPDATE STG.KIC_STG_MOOCS_COURSES set START_DATE=NULL;
UPDATE STG.KIC_STG_MOOCS_COURSES set END_DATE=NULL;

TRUNCATE TABLE ODS.KIC_SRC_MOOCS_COURSES;
ALTER TABLE ODS.KIC_SRC_MOOCS_COURSES DROP INDEX ix_courses_course_id;

INSERT INTO ODs.KIC_SRC_MOOCS_COURSES
SELECT * FROM STG.KIC_STG_MOOCS_COURSES;

CREATE UNIQUE INDEX ix_courses_course_id ON ODS.KIC_SRC_MOOCS_COURSES ( STUDIO_ID );

-- ------------------------------------------------------
-- LOAD ODS.KIC_SRC_MOOCS_USER_LOCATION
-- ------------------------------------------------------
TRUNCATE TABLE ODS.KIC_SRC_MOOCS_USER_LOCATION;
ALTER TABLE ODS.KIC_SRC_MOOCS_USER_LOCATION DROP INDEX ix_courses_course_id;

INSERT INTO ODS.KIC_SRC_MOOCS_USER_LOCATION
SELECT * FROM STG.KIC_STG_MOOCS_USER_LOCATION;

CREATE UNIQUE INDEX ix_courses_course_id ON ODS.KIC_SRC_MOOCS_USER_LOCATION ( USER_ID );

-- ------------------------------------------------------
-- LOAD STG.KIC_SRC_MOOCS_IDB_LOCATION
-- ------------------------------------------------------
TRUNCATE TABLE ODS.KIC_SRC_MOOCS_IDB_LOCATION;
ALTER TABLE ODS.KIC_SRC_MOOCS_IDB_LOCATION DROP INDEX ix_idblocation_sigla_idbx;

INSERT INTO ODS.KIC_SRC_MOOCS_IDB_LOCATION
SELECT * FROM STG.KIC_STG_MOOCS_IDB_LOCATION;

CREATE UNIQUE INDEX ix_idblocation_sigla_idbx ON ODS.KIC_SRC_MOOCS_IDB_LOCATION ( SIGLA_IDBX );

-- ------------------------------------------------------
--  SRC AUX TABLES
-- ------------------------------------------------------

-- ------------------------------------------------------
-- LOAD ODS.KIC_SRC_MOOCS_STUDENTPROGRESS
-- ------------------------------------------------------
ALTER TABLE ODS.KIC_SRC_MOOCS_STUDENTPROGRESS DROP INDEX ix_student_pro_course_user_id;

TRUNCATE TABL ODS.KIC_SRC_MOOCS_STUDENTPROGRESS;

INSERT INTO ODS.KIC_SRC_MOOCS_STUDENTPROGRESS (COURSE_ID, STUDENT_ID, INTERACTION)
SELECT COURSE_ID, STUDENT_ID, COUNT(*) as INTERACTION FROM ODS.KIC_SRC_MOOCS_CW_STUDENTMODULE
WHERE STUDENT_ID>0 and COURSE_ID<>'na' GROUP BY COURSE_ID, STUDENT_ID;

CREATE UNIQUE INDEX ix_student_pro_course_user_id ON ODS.KIC_SRC_MOOCS_STUDENTPROGRESS ( COURSE_ID, STUDENT_ID );

-- ------------------------------------------------------
--  LOAD ODS KIC_ODS_MOOCS 130 segundos
-- ------------------------------------------------------
TRUNCATE TABLE ODS.KIC_ODS_MOOCS_USER_ENROLL;
INSERT INTO ODS.KIC_ODS_MOOCS_USER_ENROLL

SELECT
msp.INTERACTION/maxsp.MAX_INTERACTION*100 as PERCENTAGE_PROGRESS,
msp.INTERACTION as PROGRESS,
(SUBSTRING_INDEX(SUBSTR(mu.EMAIL, INSTR(mu.EMAIL, '@') + 1),'.',1)) as CORPORATE_DOMAIN,
mup.COUNTRY as COUNTRY,
coalesce(mcn.STUDIO_ID,me.COURSE_ID) as COURSE_ID,
me.CREATED as CREATED,
mu.DATE_JOINED as DATE_JOINED,
coalesce(mu.email,'anon') as EMAIL,
mup.GENDER as GENDER,
mup.LEVEL_OF_EDUCATION as LEVEL_OF_EDUCATION,
mc.MODE as MODE,

NULL AS passed_timestamp,

mc.GRADE as PERCENT_GRADE,
mc.STATUSV as STATUS,
me.USER_ID AS USER_ID,
mu.USERNAME as USERNAME,
mup.YEAR_OF_BIRTH as YEAR_OF_BIRTH,
1 AS ENROLLMENT,
(CASE WHEN msp.INTERACTION>0 AND msp.INTERACTION<50 THEN 1 ELSE 0 END) as EXPLORER,
(CASE WHEN msp.INTERACTION>=50 THEN 1 ELSE 0 END) as ADVANCED,
(CASE WHEN mc.GRADE>0.649 THEN 1 ELSE 0 END) as COMPLETED,
(CASE WHEN mc.STATUSV ='downloadable' THEN 1 ELSE 0 END) as CERTIFIED,
(CASE WHEN mc.STATUSV ='downloadable' THEN 'CERTIFIED'
  WHEN mc.GRADE>0.649 THEN 'COMPLETED'
  WHEN msp.INTERACTION>=50 THEN 'ADVANCED'
  WHEN msp.INTERACTION>0 THEN 'EXPLORER'
  ELSE 'ENROLLMENT' END) AS STUDENT_TYPE,

(CASE
  WHEN YEAR(me.CREATED)-mup.YEAR_OF_BIRTH < 10 then ""
  WHEN YEAR(me.CREATED)-mup.YEAR_OF_BIRTH < 18 then "<18"
  WHEN YEAR(me.CREATED)-mup.YEAR_OF_BIRTH <= 25 then "18 - 25"
  WHEN YEAR(me.CREATED)-mup.YEAR_OF_BIRTH <= 39 then "26 - 39"
  WHEN YEAR(me.CREATED)-mup.YEAR_OF_BIRTH <= 62 then "40 - 62"
  WHEN YEAR(me.CREATED)-mup.YEAR_OF_BIRTH <= 62 AND YEAR(me.CREATED)-mup.YEAR_OF_BIRTH<90 then ">63"
  ELSE ""
  END) AS GROUP_AGE,
mcn.NAME as COURSE_NAME,
mcn.SME as SME,
mcn.START_DATE as START_DATE,
mcn.END_DATE as END_DATE,
mul.IP AS IP,
mul.TM AS TM,
mul.IP_CITY_NAME as IP_CITY_NAME,
mul.IP_COUNTRY_ISO as IP_COUNTRY_ISO,
mul.IP_COUNTRY_NAME as IP_COUNTRY_NAME,
mul.IP_LATITUDE  as IP_LATITUDE,
mul.IP_LONGITUDE  as IP_LONGITUDE,
mul.IP_POSTAL_CODE  as IP_POSTAL_CODE,
mul.IP_SUBDIVISION_NAME  as IP_SUBDIVISION_NAME,
coalesce(mil.PAIS,IP_COUNTRY_NAME) as PAIS,
mil.SIGLA_BID AS SIGLA_BID,
mil.SIGLA_IDBX as SIGLA_IDBX,
mil.SIGLA_INTERNACIONAL as SIGLA_INTERNACIONAL,
mil.REGION as REGION,
mil.IDB_GROUP_CODE as IDB_GROUP,
mil.REGION_NM as REGION_NM
FROM
ODS.KIC_SRC_MOOCS_ENROLLMENT me
LEFT JOIN
ODS.KIC_SRC_MOOCS_CERTIFICATES mc ON me.COURSE_ID=mc.COURSE_ID AND me.USER_ID=mc.USER_ID
LEFT JOIN
ODS.KIC_SRC_MOOCS_COURSES mcn ON me.COURSE_ID=mcn.STUDIO_ID2
LEFT JOIN
ODS.KIC_SRC_MOOCS_USER mu ON me.USER_ID=mu.ID
LEFT JOIN
ODS.KIC_SRC_MOOCS_USERPROFILE mup ON mu.id=mup.USER_ID
LEFT JOIN
ODS.KIC_SRC_MOOCS_USER_LOCATION mul ON mu.id=mul.USER_ID
LEFT JOIN
ODS.KIC_SRC_MOOCS_IDB_LOCATION mil ON mup.country=mil.SIGLA_IDBX
LEFT JOIN
ODS.KIC_SRC_MOOCS_STUDENTPROGRESS msp ON me.USER_ID=msp.STUDENT_ID AND me.COURSE_ID=msp.COURSE_ID
LEFT JOIN
(SELECT COURSE_ID, MAX(INTERACTION) as MAX_INTERACTION FROM ODS.KIC_SRC_MOOCS_STUDENTPROGRESS GROUP BY COURSE_ID) maxsp
 ON me.COURSE_ID=maxsp.COURSE_ID;

TRUNCATE TABLE ODS.KIC_ODS_MOOCS_USER_ENROLL_ANONYM;
INSERT INTO ODS.KIC_ODS_MOOCS_USER_ENROLL_ANONYM
 SELECT
 	PERCENTAGE_PROGRESS
 ,	PROGRESS
 ,	CORPORATE_DOMAIN
 ,	COUNTRY
 ,	COURSE_ID
 ,	CREATED
 ,	DATE_JOINED
 ,	'anon' as EMAIL
 ,	GENDER
 ,	LEVEL_OF_EDUCATION
 ,	MODE
 ,	PASSED_TIMESTAMP
 ,	PERCENT_GRADE
 ,	STATUS
 ,	MD5(USER_ID) as USER_ID
 ,	'anon' as USERNAME
 ,	YEAR_OF_BIRTH
 ,	ENROLLMENT
 ,	EXPLORER
 ,	ADVANCED
 ,	COMPLETED
 ,	CERTIFIED
 ,	STUDENT_TYPE
 ,	GROUP_AGE
 ,	COURSE_NAME
 ,	SME
 ,	START_DATE
 ,	END_DATE
 ,	IP
 ,	TM
 ,	IP_CITY_NAME
 ,	IP_COUNTRY_ISO
 ,	IP_COUNTRY_NAME
 ,	IP_LATITUDE
 ,	IP_LONGITUDE
 ,	IP_POSTAL_CODE
 ,	IP_SUBDIVISION_NAME
 ,	PAIS
 ,	SIGLA_BID
 ,	SIGLA_IDBX
 ,	SIGLA_INTERNACIONAL
 ,	REGION
 ,	IDB_GROUP
 ,	NOMBRE_REGION
 from KIC_ODS_MOOCS;
