-- ------------------------------------------------------
--  LOAD ODS KIC_ODS_MOOCS
-- ------------------------------------------------------
SELECT
msp.INTERACTIONS/maxsp.MAX_INTERACTIONS*100 as PERCENTAGE_PROGRESS,
msp.INTERACTIONS as PROGRESS,
(SUBSTRING_INDEX(SUBSTR(mu.EMAIL, INSTR(mu.EMAIL, '@') + 1),'.',1)) as CORPORATE_DOMAIN,
mup.COUNTRY as COUNTRY,
me.COURSE_ID as COURSE_ID,
me.CREATED as CREATED,
mu.DATE_JOINED as DATE_JOINED,
coalesce(mu.email,'anon') as EMAIL,
mup.GENDER as GENDER,
mup.LEVEL_OF_EDUCATION as LEVEL_OF_EDUCATION,
mc.MODE as MODE,
passed_timestamp varchar(50) DEFAULT NULL,	grades_persistentcoursegrade	passed_timestamp
mc.PERCENT_GRADE as PERCENT_GRADE,
mc.STATUS as STATUS,
me.USER_ID AS USER_ID,
mu.USERNAME as USERNAME,
mup.YEAR_OF_BIRTH as YEAR_OF_BIRTH,
1 AS ENROLLMENT,
(CASE WHEN msp.INTERACTIONS>0 AND msp.INTERACTIONS<50 THEN 1 ELSE 0 END) as EXPLORER;
(CASE WHEN msp.INTERACTIONS>=50 THEN 1 ELSE 0 END) as ADVANCED;
(CASE WHEN mc.PERCENT_GRADE>0.649 THEN 1 ELSE 0 END) as COMPLETED
(CASE WHEN mc.STATUS ='downloadable' THEN 1 ELSE 0 END) as CERTIFIED,
(CASE WHEN mc.STATUS ='downloadable' THEN 'CERTIFIED'
      WHEN mc.PERCENT_GRADE>0.649 THEN 'COMPLETED'
      WHEN msp.INTERACTIONS>=50 THEN 'ADVANCED'
      WHEN msp.INTERACTIONS>0 THEN 'EXPLORER'
      ELSE 'ENROLLMENT' END) AS STUDENT_TYPE,

(CASE
      WHEN YEAR(me.CREATED)-mu.YEAR_OF_BIRTH < 10 then ""
      WHEN YEAR(me.CREATED)-mu.YEAR_OF_BIRTH < 18 then "<18"
      WHEN YEAR(me.CREATED)-mu.YEAR_OF_BIRTH <= 25 then "18 - 25"
      WHEN YEAR(me.CREATED)-mu.YEAR_OF_BIRTH <= 39 then "26 - 39"
      WHEN YEAR(me.CREATED)-mu.YEAR_OF_BIRTH <= 62 then "40 - 62"
      WHEN YEAR(me.CREATED)-mu.YEAR_OF_BIRTH <= 62 AND YEAR(me.CREATED)-mu.YEAR_OF_BIRTH<90 then ">63"
      ELSE ""
  END) AS GROUP_AGE,
mcn.COURSE_NAME as COURSE_NAME,
mcn.SME as SME,
mcn.START_DATE as START_DATE,
mcn.END_DATE as END_DATE,
mul.IP AS IP,
mul.TM AS TM,
mul.IP_CITY_NAME as IP_CITY_NAME,
mul.IP_COUNTRY_ISO as IP_COUNTRY_ISO,
mul.IP_COUNTRY_NAME as IP_COUNTRY_NAME,
mul.IP_LATITUDE  as IP_LATITUDE,
mul.IP_LONGITUDE  as IP_LONGITUDE,
mul.IP_POSTAL_CODE  as IP_POSTAL_CODE,
mul.IP_SUBDIVISION_NAME  as IP_SUBDIVISION_NAME,
mil.PAIS as PAIS,
mil.SIGLA_BID AS SIGLA_BID,
mil.SIGLA_IDBX as SIGLA_IDBX,
mil.SIGLA_INTERNACIONAL as SIGLA_INTERNACIONAL,
mil.REGION as REGION,
mil.IDB_GROUP as IDB_GROUP,
mil.REGION_NM as REGION_NM
FROM
ODS.KIC_SRC_MOOCS_ENROLLMENT me
LEFT JOIN
ODS.KIC_SRC_MOOCS_CERTIFICATES mc
LEFT JOIN
ODS.KIC_SRC_MOOCS_COURSES mcn ON me.COURSE_ID=mc.STUDIO_ID
LEFT JOIN
ODS.KIC_SRC_MOOCS_USER mu ON me.USER_ID=mu.ID
LEFT JOIN
ODS.KIC_SRC_MOOCS_USERPROFILE mup ON mu.id=mup.USER_ID
LEFT JOIN
ODS.KIC_SRC_MOOCS_USER_LOCATION mul ON mu.id=mul.USER_ID
LEFT JOIN
ODS.KIC_SRC_MOOCS_IDB_LOCATION mil ON mup.country=mil.SIGLA_IDBX
LEFT JOIN
ODS.KIC_SRC_MOOCS_STUDENTPROGRESS msp ON me.USER_ID=msp.STUDENT_ID AND me.COURSE_ID=msp.COURSE_ID
LEFT JOIN
(SELECT COURSE_ID, MAX(INTERACTIONS) MAX_INTERACTIONS from ODS.KIC_SRC_MOOCS_STUDENTPROGRESS GROUP BY COURSE_ID) as maxsp
 join me.COURSE_ID=maxsp.COURSE_ID;
