-- ------------------------------------------------------
--  DDL for Table ODS.KIC_SRC_MOOCS_USER
-- ------------------------------------------------------
DROP TABLE IF EXISTS ODS.KIC_SRC_MOOCS_USER ;
CREATE TABLE ODS.KIC_SRC_MOOCS_USER (
  ID INT(11),
  USERNAME VARCHAR(100),
  FIRST_NAME VARCHAR(30),
  LAST_NAME VARCHAR(30),
  EMAIL VARCHAR(75),
  PASSWORD VARCHAR(128),
  IS_STAFF INT(11),
  IS_ACTIVE INT(11),
  IS_SUPERUSER INT(11),
  LAST_LOGIN DATETIME(6),
  DATE_JOINED DATETIME(6),
  STG_EXT_TS TIMESTAMP(6),
  TRAN_TYP VARCHAR(10)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;

-- ------------------------------------------------------
--  DDL for Table STG.KIC_MOOCS_USERPROFILE
-- ------------------------------------------------------
DROP TABLE IF EXISTS ODS.KIC_SRC_MOOCS_USERPROFILE;

CREATE TABLE ODS.KIC_SRC_MOOCS_USERPROFILE (
  ID INT(11),
  NAME VARCHAR(255),
  META VARCHAR(3000),
  GENDER VARCHAR(6),
  YEAR_OF_BIRTH INT(11),
  LEVEL_OF_EDUCATION VARCHAR(6),
  GOALS VARCHAR(4000),
  ALLOW_CERTIFICATE SMALLINT(6),
  COUNTRY VARCHAR(2),
  CITY VARCHAR(100),
  BIO VARCHAR(3000),
  PROFILE_IMAGE_UPLOADED_AT DATETIME(6),
  USER_ID INT(11),
  STG_EXT_TS TIMESTAMP(6),
  TRAN_TYP VARCHAR(10)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- ------------------------------------------------------
--  DDL for Table ODS.KIC_SRC_MOOCS_CERTIFICATES
-- ------------------------------------------------------
DROP TABLE IF EXISTS ODS.KIC_SRC_MOOCS_CERTIFICATE;

CREATE TABLE ODS.KIC_SRC_MOOCS_CERTIFICATES
(
  ID INT(11),
  DOWNLOAD_URL VARCHAR(128),
  GRADE DOUBLE,
  COURSE_ID VARCHAR(255),
  KEYV VARCHAR(32),
  STATUSV VARCHAR(32),
  VERIFY_UUID VARCHAR(32),
  DOWNLOAD_UUID VARCHAR(32),
  NAME VARCHAR(255),
  CREATED_DATE DATETIME(6),
  MODIFIED_DATE DATETIME(6),
  ERROR_REASON VARCHAR(512),
  MODE VARCHAR(32),
  USER_ID INT(11),
  STG_EXT_TS TIMESTAMP(6),
  TRAN_TYP VARCHAR(10)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- ------------------------------------------------------
--  DDL for Table ODS.KIC_SRC_MOOCS_CW_STUDENTMODULE
-- ------------------------------------------------------
DROP TABLE IF EXISTS ODS.KIC_SRC_MOOCS_CW_STUDENTMODULE;

CREATE TABLE ODS.KIC_SRC_MOOCS_CW_STUDENTMODULE
(
  ID INT(11) ,
  MODULE_TYPE VARCHAR(32),
  MODULE_ID VARCHAR(255),
  GRADE DOUBLE,
  CREATED DATETIME(6),
  MODIFIED DATETIME(6),
  MAX_GRADE DOUBLE,
  DONE VARCHAR(8),
  COURSE_ID VARCHAR(255),
  STUDENT_ID INT(11),
  STG_EXT_TS TIMESTAMP(6),
  TRAN_TYP VARCHAR(10)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- ------------------------------------------------------
--  DDL for Table ODS.KIC_SRC_MOOCS_COURSEGRADE
-- ------------------------------------------------------
DROP TABLE IF EXISTS ODS.KIC_SRC_MOOCS_COURSEGRADE;

CREATE TABLE ODS.KIC_SRC_MOOCS_COURSEGRADE (
  ID INT(11),
  COURSE_ID VARCHAR(255),
  GRADING_POLICY_HASH VARCHAR(255),
  PERCENT_GRADE DOUBLE,
  LETTER_GRADE VARCHAR(255),
  PASSED_TIMESTAMP DATETIME(6),
  CREATED DATETIME(6),
  MODIFIED DATETIME(6),
  USER_ID INT(11),
  STG_EXT_TS TIMESTAMP(6),
  TRAN_TYP VARCHAR(10)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- ------------------------------------------------------
--  DDL for Table ODS.KIC_SRC_MOOCS_SUBSECTIONGRADE
-- ------------------------------------------------------
DROP TABLE IF EXISTS ODS.KIC_SRC_MOOCS_SUBSECTIONGRADE;

CREATE TABLE ODS.KIC_SRC_MOOCS_SUBSECTIONGRADE (
  ID INT(11),
  COURSE_ID VARCHAR(255),
  USAGE_KEY VARCHAR(255),
  EARNED_ALL DOUBLE,
  POSSIBLE_ALL DOUBLE,
  EARNED_GRADED DOUBLE,
  POSSIBLE_GRADED DOUBLE,
  FIRST_ATTEMPTED DATETIME(6),
  CREATED DATETIME(6),
  MODIFIED DATETIME(6),
  USER_ID INT(11),
  STG_EXT_TS TIMESTAMP(6),
  TRAN_TYP VARCHAR(10)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- ------------------------------------------------------
--  DDL for Table ODS.KIC_SRC_MOOCS_ANONYMOUSUSERID
-- ------------------------------------------------------

DROP TABLE IF EXISTS ODS.KIC_SRC_MOOCS_ANONYMOUSUSERID;

CREATE TABLE ODS.KIC_SRC_MOOCS_ANONYMOUSUSERID (
  ID INT(11),
  ANONYMOUS_USER_ID VARCHAR(32),
  COURSE_ID VARCHAR(255),
  USER_ID INT(11),
  STG_EXT_TS TIMESTAMP(6),
  TRAN_TYP VARCHAR(10)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- ------------------------------------------------------
--  DDL for Table ODS.KIC_SRC_MOOCS_STUDENTROLE
-- ------------------------------------------------------
DROP TABLE IF EXISTS KIC_SRC_MOOCS_STUDENTROLE;

CREATE TABLE ODS.KIC_SRC_MOOCS_STUDENTROLE (
  ID INT(11),
  COURSE_ID VARCHAR(255),
  ROLE VARCHAR(255),
  USER_ID INT(11),
  STG_EXT_TS TIMESTAMP(6),
  TRAN_TYP VARCHAR(10)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- ------------------------------------------------------
--  DDL for Table ODS.KIC_SRC_MOOCS_ENROLLMENT
-- ------------------------------------------------------
DROP TABLE IF EXISTS ODS.KIC_SRC_MOOCS_ENROLLMENT ;

CREATE TABLE ODS.KIC_SRC_MOOCS_ENROLLMENT (
  ID INT(11),
  COURSE_ID VARCHAR(255),
  CREATED DATETIME(6),
  IS_ACTIVE SMALLINT(6),
  MODE VARCHAR(100),
  USER_ID INT(11),
  STG_EXT_TS TIMESTAMP(6),
  TRAN_TYP VARCHAR(10)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- ------------------------------------------------------
--  DDL for Table ODS.KIC_SRC_MOOCS_STUDENTLANG
-- ------------------------------------------------------
DROP TABLE IF EXISTS ODs.KIC_SRC_MOOCS_STUDENTLANG;

CREATE TABLE ODS.KIC_SRC_MOOCS_STUDENTLANG (
  ID INT(11),
  CODE VARCHAR(16),
  USER_PROFILE_ID INT(11),
  STG_EXT_TS TIMESTAMP(6),
  TRAN_TYP VARCHAR(10)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- ------------------------------------------------------
--  DDL for Table ODS.KIC_SRC_MOOCS_USER_TO_ID
-- ------------------------------------------------------
DROP TABLE IF EXISTS ODs.KIC_SRC_MOOCS_USER_TO_ID;

CREATE TABLE ODS.KIC_SRC_MOOCS_USER_TO_ID (
  HASH_ID VARCHAR(40),
  ID INT(11),
  USERNAME VARCHAR(100),
  STG_EXT_TS TIMESTAMP(6),
  TRAN_TYP VARCHAR(10)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


-- ------------------------------------------------------
--  DDL for Table ODS.KIC_SRC_MOOCS_COURSES
-- ------------------------------------------------------
DROP TABLE IF EXISTS ODs.KIC_SRC_MOOCS_COURSES;

CREATE TABLE ODS.KIC_SRC_MOOCS_COURSES (
  ID VARCHAR(50),
  STUDIO_ID VARCHAR(50),
  STUDIO_ID2 VARCHAR(50),
  NAME VARCHAR(255),
  SME VARCHAR(50),
  START_DATE DATETIME,
  END_DATE DATETIME,
  STG_EXT_TS TIMESTAMP(6),
  TRAN_TYP VARCHAR(10)
) ENGINE=InnoDB CHARSET=utf8mb4 COLLATE=utf8mb4_spanish_ci;

-- ------------------------------------------------------
--  DDL for Table ODS.KIC_SRC_MOOCS_USER_LOCATION
-- ------------------------------------------------------
DROP TABLE IF EXISTS ODS.KIC_SRC_MOOCS_USER_LOCATION;

CREATE TABLE ODS.KIC_SRC_MOOCS_USER_LOCATION (
  USER_ID INT(11),
  TM TIMESTAMP(6),
  IP VARCHAR(50),
  IP_CITY_NAME VARCHAR(100),
  IP_COUNTRY_ISO VARCHAR(100),
  IP_COUNTRY_NAME VARCHAR(100),
  IP_LATITUDE VARCHAR(100),
  IP_LONGITUDE VARCHAR(100),
  IP_POSTAL_CODE VARCHAR(100),
  IP_SUBDIVISION_NAME VARCHAR(100),
  STG_EXT_TS TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  TRAN_TYP VARCHAR(10)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- ------------------------------------------------------
--  DDL for Table STG.KIC_SRC_MOOCS_IDB_LOCATION
-- ------------------------------------------------------
DROP TABLE IF EXISTS ODS.KIC_SRC_MOOCS_IDB_LOCATION;

CREATE TABLE ODS.KIC_SRC_MOOCS_IDB_LOCATION (
  PAIS varchar(100) COMMENT 'Pais',
  SIGLA_BID varchar(5)  COMMENT 'Sigla del BID',
  SIGLA_IDBX varchar(5) COMMENT 'Sigla usada en la base de dato IDBx',
  SIGLA_INTERNACIONAL varchar(5) COMMENT 'Sigla internacional (tres letras)',
  REGION  varchar(100),
  IDB_GROUP_CODE varchar(10),
  REGION_NM varchar(100),
  STG_EXT_TS TIMESTAMP(6),
  TRAN_TYP VARCHAR(10)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- ------------------------------------------------------
--  SRC AUX TABLES
-- ------------------------------------------------------

-- ------------------------------------------------------
--  DDL for Table ODS.KIC_SRC_MOOCS_STUDENTPROGRESS
-- ------------------------------------------------------
DROP TABLE IF EXISTS ODS.KIC_SRC_MOOCS_STUDENTPROGRESS;

CREATE TABLE ODS.KIC_SRC_MOOCS_STUDENTPROGRESS
(
  COURSE_ID VARCHAR(255),
  STUDENT_ID INT(11),
  INTERACTION INT(11) ,
  STG_EXT_TS TIMESTAMP(6),
  TRAN_TYP VARCHAR(10)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- ------------------------------------------------------
--  ODS KIC_ODS_MOOCS_USER_ENROLLMENT / Masterfile
-- ------------------------------------------------------
DROP TABLE IF EXISTS ODS.KIC_ODS_MOOCS_USER_ENROLL;
CREATE TABLE ODS.KIC_ODS_MOOCS_USER_ENROLL (
  PERCENTAGE_PROGRESS int(11) DEFAULT NULL,
  PROGRESS int(11) DEFAULT NULL,
  CORPORATE_DOMAIN varchar(100) DEFAULT NULL,
  COUNTRY varchar(4) DEFAULT NULL,
  COURSE_ID varchar(50) NOT NULL,
  CREATED datetime DEFAULT NULL,
  DATE_JOINED datetime DEFAULT NULL,
  EMAIL varchar(100) DEFAULT NULL,
  GENDER varchar(5) DEFAULT NULL,
  LEVEL_OF_EDUCATION varchar(5) DEFAULT NULL,
  MODE varchar(50) DEFAULT NULL,
  PASSED_TIMESTAMP varchar(50) DEFAULT NULL,
  PERCENT_GRADE decimal(8,4) DEFAULT NULL,
  STATUS varchar(50) DEFAULT NULL,
  USER_ID int(11) DEFAULT NULL,
  USERNAME varchar(100) DEFAULT '',
  YEAR_OF_BIRTH int(11) DEFAULT NULL,
  ENROLLMENT int(11) NOT NULL,
  EXPLORER int(11) NOT NULL,
  ADVANCED int(11) NOT NULL,
  COMPLETED int(11) NOT NULL,
  CERTIFIED int(11) NOT NULL,
  STUDENT_TYPE varchar(50) NOT NULL DEFAULT '',
  GROUP_AGE varchar(50) DEFAULT NULL,
  COURSE_NAME varchar(255) DEFAULT '',
  SME varchar(100) DEFAULT '',
  START_DATE date DEFAULT NULL,
  END_DATE date DEFAULT NULL,
  IP varchar(50) DEFAULT NULL,
  TM varchar(50) DEFAULT NULL,
  IP_CITY_NAME varchar(100) DEFAULT NULL,
  IP_COUNTRY_ISO varchar(100) DEFAULT NULL,
  IP_COUNTRY_NAME varchar(100) DEFAULT NULL,
  IP_LATITUDE varchar(100) DEFAULT NULL,
  IP_LONGITUDE varchar(100) DEFAULT NULL,
  IP_POSTAL_CODE varchar(100) DEFAULT NULL,
  IP_SUBDIVISION_NAME varchar(100) DEFAULT NULL,
  PAIS varchar(100) DEFAULT NULL,
  SIGLA_BID varchar(20) DEFAULT NULL,
  SIGLA_IDBX varchar(20) DEFAULT NULL,
  SIGLA_INTERNACIONAL varchar(20) DEFAULT NULL,
  REGION varchar(20) DEFAULT NULL,
  IDB_GROUP varchar(20) DEFAULT NULL,
  NOMBRE_REGION varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ------------------------------------------------------
--  ODS KIC_ODS_MOOCS_USER_ENROLL_ANONYM/ Masterfile anonym
-- ------------------------------------------------------
DROP TABLE IF EXISTS ODS.KIC_ODS_MOOCS_USER_ENROLL_ANONYM;
CREATE TABLE ODS.KIC_ODS_MOOCS_USER_ENROLL_ANONYM (
  PERCENTAGE_PROGRESS int(11) DEFAULT NULL,
  PROGRESS int(11) DEFAULT NULL,
  CORPORATE_DOMAIN varchar(100) DEFAULT NULL,
  COUNTRY varchar(4) DEFAULT NULL,
  COURSE_ID varchar(50) NOT NULL,
  CREATED datetime DEFAULT NULL,
  DATE_JOINED datetime DEFAULT NULL,
  EMAIL varchar(100) DEFAULT NULL,
  GENDER varchar(5) DEFAULT NULL,
  LEVEL_OF_EDUCATION varchar(5) DEFAULT NULL,
  MODE varchar(50) DEFAULT NULL,
  PASSED_TIMESTAMP varchar(50) DEFAULT NULL,
  PERCENT_GRADE decimal(8,4) DEFAULT NULL,
  STATUS varchar(50) DEFAULT NULL,
  USER_ID varchar(100) DEFAULT NULL,
  USERNAME varchar(100) DEFAULT '',
  YEAR_OF_BIRTH int(11) DEFAULT NULL,
  ENROLLMENT int(11) NOT NULL,
  EXPLORER int(11) NOT NULL,
  ADVANCED int(11) NOT NULL,
  COMPLETED int(11) NOT NULL,
  CERTIFIED int(11) NOT NULL,
  STUDENT_TYPE varchar(50) NOT NULL DEFAULT '',
  GROUP_AGE varchar(50) DEFAULT NULL,
  COURSE_NAME varchar(255) DEFAULT '',
  SME varchar(100) DEFAULT '',
  START_DATE date DEFAULT NULL,
  END_DATE date DEFAULT NULL,
  IP varchar(50) DEFAULT NULL,
  TM varchar(50) DEFAULT NULL,
  IP_CITY_NAME varchar(100) DEFAULT NULL,
  IP_COUNTRY_ISO varchar(100) DEFAULT NULL,
  IP_COUNTRY_NAME varchar(100) DEFAULT NULL,
  IP_LATITUDE varchar(100) DEFAULT NULL,
  IP_LONGITUDE varchar(100) DEFAULT NULL,
  IP_POSTAL_CODE varchar(100) DEFAULT NULL,
  IP_SUBDIVISION_NAME varchar(100) DEFAULT NULL,
  PAIS varchar(100) DEFAULT NULL,
  SIGLA_BID varchar(20) DEFAULT NULL,
  SIGLA_IDBX varchar(20) DEFAULT NULL,
  SIGLA_INTERNACIONAL varchar(20) DEFAULT NULL,
  REGION varchar(20) DEFAULT NULL,
  IDB_GROUP varchar(20) DEFAULT NULL,
  NOMBRE_REGION varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
;
