-- ------------------------------------------------------
--  DDL for Table ODS.KIC_SRC_MOOCS_USER
-- ------------------------------------------------------
CREATE TABLE ODS.KIC_SRC_MOOCS_USER (
  ID INT(11),
  USERNAME VARCHAR(100),
  FIRST_NAME VARCHAR(30),
  LAST_NAME VARCHAR(30),
  EMAIL VARCHAR(75),
  PASSWORD VARCHAR(128),
  IS_STAFF INT(11),
  IS_ACTIVE INT(11),
  IS_SUPERUSER INT(11),
  LAST_LOGIN DATETIME(6),
  DATE_JOINED DATETIME(6),
  STG_EXT_TS TIMESTAMP(6),
  TRAN_TYP VARCHAR(10)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;

-- ------------------------------------------------------
--  DDL for Table STG.KIC_MOOCS_USERPROFILE
-- ------------------------------------------------------
CREATE TABLE ODS.KIC_SRC_MOOCS_USERPROFILE (
  ID INT(11),
  NAME VARCHAR(255),
  META VARCHAR(3000),
  GENDER VARCHAR(6),
  YEAR_OF_BIRTH INT(11),
  LEVEL_OF_EDUCATION VARCHAR(6),
  GOALS VARCHAR(4000),
  ALLOW_CERTIFICATE SMALLINT(6),
  COUNTRY VARCHAR(2),
  CITY VARCHAR(100),
  BIO VARCHAR(3000),
  PROFILE_IMAGE_UPLOADED_AT DATETIME(6),
  USER_ID INT(11),
  STG_EXT_TS TIMESTAMP(6),
  TRAN_TYP VARCHAR(10)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- ------------------------------------------------------
--  DDL for Table ODS.KIC_SRC_MOOCS_CERTIFICATES
-- ------------------------------------------------------

CREATE TABLE ODS.KIC_SRC_MOOCS_CERTIFICATES
(
  ID INT(11),
  DOWNLOAD_URL VARCHAR(128),
  GRADE DOUBLE,
  COURSE_ID VARCHAR(255),
  KEYV VARCHAR(32),
  STATUSV VARCHAR(32),
  VERIFY_UUID VARCHAR(32),
  DOWNLOAD_UUID VARCHAR(32),
  NAME VARCHAR(255),
  CREATED_DATE DATETIME(6),
  MODIFIED_DATE DATETIME(6),
  ERROR_REASON VARCHAR(512),
  MODE VARCHAR(32),
  USER_ID INT(11),
  STG_EXT_TS TIMESTAMP(6),
  TRAN_TYP VARCHAR(10)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- ------------------------------------------------------
--  DDL for Table ODS.KIC_SRC_MOOCS_CW_STUDENTMODULE
-- ------------------------------------------------------

CREATE TABLE ODS.KIC_SRC_MOOCS_CW_STUDENTMODULE
(
  ID INT(11) ,
  MODULE_TYPE VARCHAR(32),
  MODULE_ID VARCHAR(255),
  GRADE DOUBLE,
  CREATED DATETIME(6),
  MODIFIED DATETIME(6),
  MAX_GRADE DOUBLE,
  DONE VARCHAR(8),
  COURSE_ID VARCHAR(255),
  STUDENT_ID INT(11),
  STG_EXT_TS TIMESTAMP(6),
  TRAN_TYP VARCHAR(10)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- ------------------------------------------------------
--  DDL for Table ODS.KIC_SRC_MOOCS_COURSEGRADE
-- ------------------------------------------------------

CREATE TABLE ODS.KIC_SRC_MOOCS_COURSEGRADE (
  ID INT(11),
  COURSE_ID VARCHAR(255),
  GRADING_POLICY_HASH VARCHAR(255),
  PERCENT_GRADE DOUBLE,
  LETTER_GRADE VARCHAR(255),
  PASSED_TIMESTAMP DATETIME(6),
  CREATED DATETIME(6),
  MODIFIED DATETIME(6),
  USER_ID INT(11),
  STG_EXT_TS TIMESTAMP(6),
  TRAN_TYP VARCHAR(10)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- ------------------------------------------------------
--  DDL for Table ODS.KIC_SRC_MOOCS_SUBSECTIONGRADE
-- ------------------------------------------------------

CREATE TABLE ODS.KIC_SRC_MOOCS_SUBSECTIONGRADE (
  ID INT(11),
  COURSE_ID VARCHAR(255),
  USAGE_KEY VARCHAR(255),
  EARNED_ALL DOUBLE,
  POSSIBLE_ALL DOUBLE,
  EARNED_GRADED DOUBLE,
  POSSIBLE_GRADED DOUBLE,
  FIRST_ATTEMPTED DATETIME(6),
  CREATED DATETIME(6),
  MODIFIED DATETIME(6),
  USER_ID INT(11),
  STG_EXT_TS TIMESTAMP(6),
  TRAN_TYP VARCHAR(10)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- ------------------------------------------------------
--  DDL for Table ODS.KIC_SRC_MOOCS_ANONYMOUSUSERID
-- ------------------------------------------------------

CREATE TABLE ODS.KIC_SRC_MOOCS_ANONYMOUSUSERID (
  ID INT(11),
  ANONYMOUS_USER_ID VARCHAR(32),
  COURSE_ID VARCHAR(255),
  USER_ID INT(11),
  STG_EXT_TS TIMESTAMP(6),
  TRAN_TYP VARCHAR(10)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- ------------------------------------------------------
--  DDL for Table ODS.KIC_SRC_MOOCS_STUDENTROLE
-- ------------------------------------------------------

CREATE TABLE ODS.KIC_SRC_MOOCS_STUDENTROLE (
  ID INT(11),
  COURSE_ID VARCHAR(255),
  ROLE VARCHAR(255),
  USER_ID INT(11),
  STG_EXT_TS TIMESTAMP(6),
  TRAN_TYP VARCHAR(10)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- ------------------------------------------------------
--  DDL for Table ODS.KIC_SRC_MOOCS_ENROLLMENT
-- ------------------------------------------------------

CREATE TABLE ODS.KIC_SRC_MOOCS_ENROLLMENT (
  ID INT(11),
  COURSE_ID VARCHAR(255),
  CREATED DATETIME(6),
  IS_ACTIVE SMALLINT(6),
  MODE VARCHAR(100),
  USER_ID INT(11),
  STG_EXT_TS TIMESTAMP(6),
  TRAN_TYP VARCHAR(10)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- ------------------------------------------------------
--  DDL for Table ODS.KIC_SRC_MOOCS_STUDENTLANG
-- ------------------------------------------------------
CREATE TABLE ODS.KIC_SRC_MOOCS_STUDENTLANG (
  ID INT(11),
  CODE VARCHAR(16),
  USER_PROFILE_ID INT(11),
  STG_EXT_TS TIMESTAMP(6),
  TRAN_TYP VARCHAR(10)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- ------------------------------------------------------
--  DDL for Table ODS.KIC_SRC_MOOCS_USER_TO_ID
-- ------------------------------------------------------
CREATE TABLE ODS.KIC_SRC_MOOCS_USER_TO_ID (
  HASH_ID VARCHAR(40),
  ID INT(11),
  USERNAME VARCHAR(100),
  STG_EXT_TS TIMESTAMP(6),
  TRAN_TYP VARCHAR(10)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


-- ------------------------------------------------------
--  DDL for Table ODS.KIC_SRC_MOOCS_COURSES
-- ------------------------------------------------------
DROP TABLE IF EXISTS ODs.KIC_SRC_MOOCS_COURSES;

CREATE TABLE ODS.KIC_SRC_MOOCS_COURSES (
  ID VARCHAR(50),
  STUDIO_ID VARCHAR(50),
  STUDIO_ID2 VARCHAR(50),
  NAME VARCHAR(255),
  SME VARCHAR(50),
  START_DATE DATETIME,
  END_DATE DATETIME,
  STG_EXT_TS TIMESTAMP(6),
  TRAN_TYP VARCHAR(10)
) ENGINE=InnoDB CHARSET=utf8mb4 COLLATE=utf8mb4_spanish_ci;

-- ------------------------------------------------------
--  DDL for Table ODS.KIC_SRC_MOOCS_USER_LOCATION
-- ------------------------------------------------------
CREATE TABLE ODS.KIC_SRC_MOOCS_USER_LOCATION (
  USER_ID INT(11),
  TM TIMESTAMP(6),
  IP VARCHAR(50),
  IP_CITY_NAME VARCHAR(100),
  IP_COUNTRY_ISO VARCHAR(100),
  IP_COUNTRY_NAME VARCHAR(100),
  IP_LATITUDE VARCHAR(100),
  IP_LONGITUDE VARCHAR(100),
  IP_POSTAL_CODE VARCHAR(100),
  IP_SUBDIVISION_NAME VARCHAR(100),
  STG_EXT_TS TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  TRAN_TYP VARCHAR(10)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- ------------------------------------------------------
--  DDL for Table STG.KIC_SRC_MOOCS_IDB_LOCATION
-- ------------------------------------------------------
CREATE TABLE ODS.KIC_SRC_MOOCS_IDB_LOCATION (
  PAIS varchar(100) COMMENT 'Pais',
  SIGLA_BID varchar(5)  COMMENT 'Sigla del BID',
  SIGLA_IDBX varchar(5) COMMENT 'Sigla usada en la base de dato IDBx',
  SIGLA_INTERNACIONAL varchar(5) COMMENT 'Sigla internacional (tres letras)',
  REGION  varchar(100),
  IDB_GROUP_CODE varchar(10),
  REGION_NM varchar(100),
  STG_EXT_TS TIMESTAMP(6),
  TRAN_TYP VARCHAR(10)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- ------------------------------------------------------
--  SRC AUX TABLES
-- ------------------------------------------------------

-- ------------------------------------------------------
--  DDL for Table ODS.KIC_SRC_MOOCS_STUDENTPROGRESS
-- ------------------------------------------------------
CREATE TABLE ODS.KIC_SRC_MOOCS_STUDENTPROGRESS
(
  COURSE_ID VARCHAR(255),
  STUDENT_ID INT(11),
  INTERACTION INT(11) ,
  STG_EXT_TS TIMESTAMP(6),
  TRAN_TYP VARCHAR(10)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- ------------------------------------------------------
--  ODS KIC_ODS_MOOCS / Masterfile
-- ------------------------------------------------------
TRUNCATE TABLE ODS.KIC_ODS_MOOCS;
INSERT INTO ODS.KIC_ODS_MOOCS

SELECT
msp.INTERACTION/maxsp.MAX_INTERACTION*100 as PERCENTAGE_PROGRESS,
msp.INTERACTION as PROGRESS,
(SUBSTRING_INDEX(SUBSTR(mu.EMAIL, INSTR(mu.EMAIL, '@') + 1),'.',1)) as CORPORATE_DOMAIN,
mup.COUNTRY as COUNTRY,
me.COURSE_ID as COURSE_ID,
me.CREATED as CREATED,
mu.DATE_JOINED as DATE_JOINED,
coalesce(mu.email,'anon') as EMAIL,
mup.GENDER as GENDER,
mup.LEVEL_OF_EDUCATION as LEVEL_OF_EDUCATION,
mc.MODE as MODE,
NULL as passed_timestamp,
mc.GRADE as PERCENT_GRADE,
mc.STATUSV as STATUS,
me.USER_ID AS USER_ID,
mu.USERNAME as USERNAME,
mup.YEAR_OF_BIRTH as YEAR_OF_BIRTH,
1 AS ENROLLMENT,
(CASE WHEN msp.INTERACTION>0 AND msp.INTERACTION<50 THEN 1 ELSE 0 END) as EXPLORER,
(CASE WHEN msp.INTERACTION>=50 THEN 1 ELSE 0 END) as ADVANCED,
(CASE WHEN mc.GRADE>0.649 THEN 1 ELSE 0 END) as COMPLETED,
(CASE WHEN mc.STATUSV ='downloadable' THEN 1 ELSE 0 END) as CERTIFIED,
(CASE WHEN mc.STATUSV ='downloadable' THEN 'CERTIFIED'
  WHEN mc.GRADE>0.649 THEN 'COMPLETED'
  WHEN msp.INTERACTION>=50 THEN 'ADVANCED'
  WHEN msp.INTERACTION>0 THEN 'EXPLORER'
  ELSE 'ENROLLMENT' END) AS STUDENT_TYPE,

(CASE
  WHEN YEAR(me.CREATED)-mup.YEAR_OF_BIRTH < 10 then ""
  WHEN YEAR(me.CREATED)-mup.YEAR_OF_BIRTH < 18 then "<18"
  WHEN YEAR(me.CREATED)-mup.YEAR_OF_BIRTH <= 25 then "18 - 25"
  WHEN YEAR(me.CREATED)-mup.YEAR_OF_BIRTH <= 39 then "26 - 39"
  WHEN YEAR(me.CREATED)-mup.YEAR_OF_BIRTH <= 62 then "40 - 62"
  WHEN YEAR(me.CREATED)-mup.YEAR_OF_BIRTH <= 62 AND YEAR(me.CREATED)-mup.YEAR_OF_BIRTH<90 then ">63"
  ELSE ""
  END) AS GROUP_AGE,
mcn.NAME as COURSE_NAME,
mcn.SME as SME,
mcn.START_DATE as START_DATE,
mcn.END_DATE as END_DATE,
mul.IP AS IP,
mul.TM AS TM,
mul.IP_CITY_NAME as IP_CITY_NAME,
mul.IP_COUNTRY_ISO as IP_COUNTRY_ISO,
mul.IP_COUNTRY_NAME as IP_COUNTRY_NAME,
mul.IP_LATITUDE  as IP_LATITUDE,
mul.IP_LONGITUDE  as IP_LONGITUDE,
mul.IP_POSTAL_CODE  as IP_POSTAL_CODE,
mul.IP_SUBDIVISION_NAME  as IP_SUBDIVISION_NAME,
mil.PAIS as PAIS,
mil.SIGLA_BID AS SIGLA_BID,
mil.SIGLA_IDBX as SIGLA_IDBX,
mil.SIGLA_INTERNACIONAL as SIGLA_INTERNACIONAL,
mil.REGION as REGION,
mil.IDB_GROUP_CODE as IDB_GROUP,
mil.REGION_NM as REGION_NM
FROM
ODS.KIC_SRC_MOOCS_ENROLLMENT me
LEFT JOIN
ODS.KIC_SRC_MOOCS_CERTIFICATES mc ON me.COURSE_ID=mc.COURSE_ID AND me.USER_ID=mc.USER_ID
LEFT JOIN
ODS.KIC_SRC_MOOCS_COURSES mcn ON me.COURSE_ID=mcn.STUDIO_ID
LEFT JOIN
ODS.KIC_SRC_MOOCS_USER mu ON me.USER_ID=mu.ID
LEFT JOIN
ODS.KIC_SRC_MOOCS_USERPROFILE mup ON mu.id=mup.USER_ID
LEFT JOIN
ODS.KIC_SRC_MOOCS_USER_LOCATION mul ON mu.id=mul.USER_ID
LEFT JOIN
ODS.KIC_SRC_MOOCS_IDB_LOCATION mil ON mup.country=mil.SIGLA_IDBX
LEFT JOIN
ODS.KIC_SRC_MOOCS_STUDENTPROGRESS msp ON me.USER_ID=msp.STUDENT_ID AND me.COURSE_ID=msp.COURSE_ID
LEFT JOIN
(SELECT COURSE_ID, MAX(INTERACTION) as MAX_INTERACTION FROM ODS.KIC_SRC_MOOCS_STUDENTPROGRESS GROUP BY COURSE_ID) maxsp
 ON me.COURSE_ID=maxsp.COURSE_ID;
